### ISSUE TITLE
Can't run an example

### ISSUE THREAD

**Issue by igorkovalchuk** [zcreativelabs/react-simple-maps#135]
npm --version
6.4.1

Example: basic-map

npm install 
npm run dev
open http://localhost:3000

Error in ./pages/index.js

Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/home/lampshade10/Downloads/react-simple-maps-master/package.json" at 0, attempted to resolve relative to "/home/lampshade10/Downloads/react-simple-maps-master"
    at /home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-loader/lib/index.js:50:20)
    at /home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/home/lampshade10/Downloads/react-simple-maps-master/examples/basic-map/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)

**Comment by igorkovalchuk** [comment]
FYI: this is an issue with package.json dependencies.
These (current versions) works:
  "dependencies": {
    "next": "^8.1.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-simple-maps": "^0.12.1"
  }

**Comment by igorkovalchuk** [comment]
And I can't fix the with-redux-tooltip ...
